### ISSUE TITLE
Improved system diagram

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/ai-readiness#28]
Currently we have this:

![Diagram](https://cdn.mathpix.com/cropped/2024_07_03_22477cb218b8b3685bb0g-1.jpg?height=1198&width=1648&top_left_y=1233&top_left_x=236)

It needs improving!

**Comment by lucaborella89** [comment]
@mcoimbat fyi

**Comment by vicenteherrera** [comment]
I'm working a lot on diagrams, this is my WIP for a new version of this.

It's not finished and I have to double check the numbers of the threats assigned makes sense, but given the date I want to share now to gather possible feedback soonish.

Some of my ideas included in this new version:
* Show interactions starting at the top, to bottom, when possible in sequential order, including both in and out in all cases
* Rename "chat.com" that generates a lots of questions in meetings to "Inferenece Environment", that for the current scope is Saas, but in the future will have additional alternatives (self managed open source, etc).
* Include a separate diagram for vector database information loading. I still have to review our list of threats and position the right numbers there.
* I include here the posibility of the inference engine collecting additional information from Internet, but will remove this for the final version of the diagram as I belive we considered it out of scope for this version.

¡Please leave any comments!

![ai_rag_security5](https://github.com/user-attachments/assets/ce8f1bf8-375d-4c5b-b50b-cad93ceb6f52)

**Comment by vicenteherrera** [comment]
That is an interesting proposition. It will make a cleaner version for sure. But I think it also gives value mapping in a graphical way all threats, and may be worth the effort to keep updated.

Here are two new proposals, one without markins, another one using a different way, instead of just the number, the id nomenclature we are using for TR-n. We can use one or both for this release, and if it becomes a burden to keep updated, just revert to only show the one without any threat identified.

To draw this I've gone through all threats and chosen where I think it makes more sense to position them on these new diagrams, but some of my decisions are my own interpretation. Some threats describe an scenario where several parts of the system play an important role, so we should not think the diagram as an absolute indication of where it lies.

Something I'm seeing is that we have related threats, for example about the vector database, not listed consecutively. But even if we decide to reorder the numbering, when the time comes to add more, we will again not have them sorted in a particular order, so it's not worth trying anyways. When we extend the scope and end up with a lot of threat described, maybe it will be worth using a schema like TR-X.Y, where the use first number to group threats affecting the same component. But right now I think it's overkill.

The "artistic style" has not been my focus, but can also be commented. Please leave feedback!

![ai_rag_security drawio](https://github.com/user-attachments/assets/ce46151f-0dd2-4826-991b-0b21391268c2)

**Comment by ColinEberhardt** [comment]
Really like these diagrams, and I must admit, seeing the to side-by-side, I prefer the one with the threats indicated directly on the diagram. It really helps understand the overall landscape.

Are you OK to raise a PR with this new graphic? Is there a suitable source format that could be added to the repo too?

> When we extend the scope and end up with a lot of threat described, maybe it will be worth using a schema like TR-X.Y, where the use first number to group threats affecting the same component.

Good shout - there are various things about our current structure that I would like to debate and change once everything is in initial draft form. For now, can you please raise an issue with the above suggestions just so that it doesn't get forgotten?

**Comment by ColinEberhardt** [comment]
closed via #44
